### ISSUE TITLE
Should `RedisStore` use `RedisPool` instead of `RedisClient`?

### ISSUE THREAD

**Issue by maxcountryman** [maxcountryman/tower-sessions#92]
It seems like it's probably better practice to use [a pool](https://docs.rs/fred/7.0.0/fred/clients/struct.RedisPool.html) instead of a single client.

**Comment by thallada** [comment]
I'm interested in taking this on.

I recently switched to tower-sessions from async-session and I was using async-fred-session for the redis store. Their API only allows you to construct a redis store using a pool with the method `from_pool`: https://docs.rs/async-fred-session/latest/async_fred_session/struct.RedisSessionStore.html#method.from_pool

Do you think it's useful to keep around the ability to construct a store using a client and not a pool? It seems like best practice in most web servers to use a pool instead of a client.

Should we avoid making this a breaking change? I see a few options:

1. Make `RedisStore::new` take a pool instead of a client. This would be a breaking change.
2. Just add a new method `RedisStore::from_pool`. This wouldn't be a breaking change.
3. Add the `RedisStore::from_pool` method AND remove the `new` method so there isn't two ways of making a store and prevent using the less-optimal client. This would be a breaking change.
4. Add the `RedisStore::from_pool` method AND rename the `new` method to `RedisClient::from_client` so there's still the option of using a client but it's more clear that you shouldn't use a client by default but choose one or the other. This would be a breaking change.

**Comment by maxcountryman** [comment]
I don't feel strongly regarding a potential breaking change: if using a pool is always better practice, that's fine. If there are situations where you want to use a client or otherwise can't use a pool, then I think we should support both. I don't use Redis enough myself to advise well on that.
